language: node_js
node_js:
- node
notifications:
  email: false
  slack:
    secure: lTwhfqzD90P4+FJGsfIuinsI1QR09s2J4xl4Dnn2kqDHkAx63OatHUONpo1IvSLVf8FwoIWBfFIuOf6NlM4CSqmZOPYEuYPxq69613d2zT72sW6tIWt2hj/bgcc/iC3VSUvlpAJYYyNa0VMvIHIYVIjtoQjmm0TlDtuloRlJ/m7M0vfLA19cQcxNneVzYDlAeIJ5vpCDDz+0AoG8FJ5W/ODl6a8Cc/xwqpazp3Hl/xygSeugvX9mrMsFcspEfqZGLRva3iSq42tgCJpWHsFeSmglePOt9N0afG83+WDd1tbnP+N9zhpEg8n0fcCUet977N/8edspJ6JT15Fmm3dv6+GNbGcFFYHeGgpy5oCnjHWSb1MJSBT2jtxn6RB9K1QuwP+QwO/Xl0rGwp4HhtjtEfRvXBC5WisI1ZxBB4M1C+wNxy/Vnhb8lxrR9gTr1hOXGQMkDxM7gpg8y9DkEy3G2HFsvugSfggdR0UoN5aJ1uQCQf5t2SxsNUe5XvXxT+BtxjHX6Jzen5Smbg/UXXD7OsWMWWt9cg13OmsZlQZiaEzA5ZIg9NwzyDNEt8wlG5AEbexgT8/8XaflVbBPE2QWcpUUtwBRBXTc/BkJXJWZkpc1xNbt7QqDsBM1cHQ5ajVBsSPYJ445hPeiSKOEiUsqu//e3/PKVYZ6qo6tJpvtFNY=
